---
version: 2
jobs:
  build:
    docker:
      - image: cppchriscpp/cc65-node:latest
    steps:
      - checkout
      - run:
          name: Move tools folder to expected location
          command: cp -rf /tools .
      - run:
          name: Build the game itself
          command: make
      - store_artifacts:
          path: ./rom