version: 2
jobs:
  build:
    docker:
      - image: cppchriscpp/cc65-node:latest
    steps:
      - checkout
      - run:
          name: Move tools folder to expected location
          command: cp -rf /tools .
      - run:
          name: "Npm installs"
          command: "cd tools/tmx2c/src && npm install && cd ../../../tools/sprite_def2img/src && npm install && cd ../../../tools/chr2img/src && npm install"
      - run:
          name: Build the game itself
          command: make
      - store_artifacts:
          path: ./rom
  deploy:
    docker: 
      - image: cppchriscpp/cc65-node:latest
    steps:
      - run:
          name: Deploy new version to s3
          command: aws s3 cp ./rom/starter.nes s3://nes-starter-kit/$CIRCLE_BRANCH/starter.$CIRCLE_BUILD_NUM.nes
      - run: 
          name: Replace "latest" rom file
          command: aws s3 cp ./rom/starter.nes s3://nes-starter-kit/$CIRCLE_BRANCH/starter.latest.nes
  
workflows:
  version: 2
  build-deploy:
    jobs: 
      - build
      - deploy:
          requires:
            - build
        