---
version: 2
jobs:
  build:
    docker:
      - image: cppchriscpp:cc65-node
    steps:
      - checkout
      - run:
          name: Build the game itself
          command: make
      - store_artifacts:
          path: ./rom